# Combined preprocessing of the datasets

## Utils

In [11]:
import json
from scipy.stats import entropy

def calculate_entropy(col):
    """Calculate entropy of a column in a dataframe.
    
    Args:
        df (pandas.DataFrame): Dataframe containing the column.
        col (str): Name of the column to calculate entropy for.
        
    Returns:
        float: Entropy of the column.
    """
    value_counts = col.value_counts()
    probabilities = value_counts / value_counts.sum()
    return entropy(probabilities, base=2)

## Preprocessing Phase 2

### Overview

The goal of this second part is to combine the different datasources that have been partially processed.

In [4]:
import pandas as pd

In [5]:
PACKAGE_DATA_PREPROCESSED_DATASET_PATH = "../datasets/preprocessed/eval_package_data_formatted.json"
df_package_data = pd.read_json(PACKAGE_DATA_PREPROCESSED_DATASET_PATH)
df_package_data

,RouteID,StopID,PackageID,planned_service_time_seconds,depth_cm,height_cm,weight_cm
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,AH,PackageID_fd17bd67-a3d8-45b9-936b-c7e9d879102e,31.5,40.6,12.7,30.5
1,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,AH,PackageID_f78261e7-4c8c-4d72-b007-9934a53a700b,31.5,25.4,12.7,17.8
2,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,AJ,PackageID_a8e394ee-4208-412d-8b34-8cbce880a322,40.0,25.4,12.7,17.8
3,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,AL,PackageID_b7c39ed4-fa0a-497a-ae0c-e3515734f8ae,47.0,37.1,6.1,21.8
4,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,AL,PackageID_e980c24b-ab88-4af1-b3f9-1f851823f561,47.0,44.5,20.3,35.6
...,...,...,...,...,...,...,...
724908,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,YU,PackageID_b0bad72b-041e-4b5b-8303-03131c837b8d,38.3,66.0,17.8,40.6
724909,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,YU,PackageID_b2c6f0de-6fcf-4616-b2cd-ba63ef6d0715,38.3,61.6,10.8,41.3
724910,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,YU,PackageID_3de4b3fd-d80d-4ae7-a519-c82a4e46c48c,38.3,48.3,30.5,36.8
724911,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,ZQ,PackageID_59aae7fe-cbb2-47c8-8c2f-59a97154ccd9,102.0,48.3,15.2,33.0
724912,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,ZS,PackageID_267d089c-6c82-49b0-80f8-6748db36c8dc,74.0,21.3,4.1,13.7

In [6]:
ROUTE_DATA_PREPROCESSED_DATASET_PATH = "../datasets/preprocessed/eval_route_data_formatted.json"

df_eval_route = pd.read_json(ROUTE_DATA_PREPROCESSED_DATASET_PATH, orient='records')
df_eval_route

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,Zone,starting_point
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ
1,RouteID_00337a3a-19c6-4821-9350-ad3cf0532047,DLA4,2018-09-03,14:48:09,3313071.00,E-4,AI
2,RouteID_0034b931-97a7-485f-a6b3-b22798489094,DLA4,2018-09-19,15:00:43,3313071.00,D-1,BU
3,RouteID_0085d8a2-71a3-4205-9c46-e62139eca47b,DSE4,2018-07-02,15:18:39,3539605.75,B-10,HI
4,RouteID_008bf177-673c-4647-89dd-bf8c13b7c51d,DLA3,2018-07-11,15:30:00,3313071.00,B-9,HP
...,...,...,...,...,...,...,...
3002,RouteID_fe892b64-84ad-48d5-aede-f65d2e4a3123,DLA7,2018-09-09,14:20:14,3313071.00,E-26,YY
3003,RouteID_feb2d877-9478-474c-8f88-6f93ce2ac6aa,DLA8,2018-06-26,16:35:12,3539605.75,D-23,OX
3004,RouteID_fedf4c2f-2618-4598-bfb5-ec90822c9a29,DBO3,2018-09-17,12:01:18,4247527.00,H-2,YL
3005,RouteID_ff30c100-6266-461d-9c56-939775a1defe,DBO1,2018-09-18,13:05:52,4247527.00,H-7,UI
3006,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL

### Data Integration

In [7]:
# merge df eval route and df package data
df_eval_route_package_data = pd.merge(df_eval_route, df_package_data, on='RouteID')
df_eval_route_package_data

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,Zone,starting_point,StopID,PackageID,planned_service_time_seconds,depth_cm,height_cm,weight_cm
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AH,PackageID_fd17bd67-a3d8-45b9-936b-c7e9d879102e,31.5,40.6,12.7,30.5
1,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AH,PackageID_f78261e7-4c8c-4d72-b007-9934a53a700b,31.5,25.4,12.7,17.8
2,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AJ,PackageID_a8e394ee-4208-412d-8b34-8cbce880a322,40.0,25.4,12.7,17.8
3,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AL,PackageID_b7c39ed4-fa0a-497a-ae0c-e3515734f8ae,47.0,37.1,6.1,21.8
4,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AL,PackageID_e980c24b-ab88-4af1-b3f9-1f851823f561,47.0,44.5,20.3,35.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
714564,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,YU,PackageID_b0bad72b-041e-4b5b-8303-03131c837b8d,38.3,66.0,17.8,40.6
714565,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,YU,PackageID_b2c6f0de-6fcf-4616-b2cd-ba63ef6d0715,38.3,61.6,10.8,41.3
714566,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,YU,PackageID_3de4b3fd-d80d-4ae7-a519-c82a4e46c48c,38.3,48.3,30.5,36.8
714567,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,ZQ,PackageID_59aae7fe-cbb2-47c8-8c2f-59a97154ccd9,102.0,48.3,15.2,33.0
714568,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,ZS,PackageID_267d089c-6c82-49b0-80f8-6748db36c8dc,74.0,21.3,4.1,13.7

### Feature Extraction

### 1. Add time to arrive feature

In [1]:
import json

TRAVEL_TIMES_RAW_DATASET_PATH = "../datasets/raw/eval_travel_times_formatted.json"

with open(TRAVEL_TIMES_RAW_DATASET_PATH,"r") as travel_times_file:
    travel_times_data = json.load(travel_times_file)

In [2]:
# Get time to reach stop from source
def get_time_to_reach_stop_from_source(route, source, stop):
    return travel_times_data[route][source][stop]

In [8]:
# Create a new column time_to_arrive that applies the get_time_to_reach_stop_from_source function to RouteID, starting_point, and StopID
df_eval_route_package_data['time_to_arrive'] = df_eval_route_package_data.apply(lambda row: get_time_to_reach_stop_from_source(row['RouteID'], row['starting_point'], row['StopID']), axis=1)
df_eval_route_package_data

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,Zone,starting_point,StopID,PackageID,planned_service_time_seconds,depth_cm,height_cm,weight_cm,time_to_arrive
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AH,PackageID_fd17bd67-a3d8-45b9-936b-c7e9d879102e,31.5,40.6,12.7,30.5,703.9
1,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AH,PackageID_f78261e7-4c8c-4d72-b007-9934a53a700b,31.5,25.4,12.7,17.8,703.9
2,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AJ,PackageID_a8e394ee-4208-412d-8b34-8cbce880a322,40.0,25.4,12.7,17.8,670.6
3,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AL,PackageID_b7c39ed4-fa0a-497a-ae0c-e3515734f8ae,47.0,37.1,6.1,21.8,789.6
4,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ,AL,PackageID_e980c24b-ab88-4af1-b3f9-1f851823f561,47.0,44.5,20.3,35.6,789.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714564,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,YU,PackageID_b0bad72b-041e-4b5b-8303-03131c837b8d,38.3,66.0,17.8,40.6,2386.8
714565,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,YU,PackageID_b2c6f0de-6fcf-4616-b2cd-ba63ef6d0715,38.3,61.6,10.8,41.3,2386.8
714566,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,YU,PackageID_3de4b3fd-d80d-4ae7-a519-c82a4e46c48c,38.3,48.3,30.5,36.8,2386.8
714567,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,ZQ,PackageID_59aae7fe-cbb2-47c8-8c2f-59a97154ccd9,102.0,48.3,15.2,33.0,2568.5
714568,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL,ZS,PackageID_267d089c-6c82-49b0-80f8-6748db36c8dc,74.0,21.3,4.1,13.7,2588.5

In [9]:
df_eval_route_package_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714569 entries, 0 to 714568
Data columns (total 14 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   RouteID                       714569 non-null  object
 1   station_code                  714569 non-null  object
 2   date_YYYY_MM_DD               714569 non-null  object
 3   departure_time_utc            714569 non-null  object
 4   executor_capacity_cm3         714569 non-null  float64
 5   Zone                          714569 non-null  object
 6   starting_point                714569 non-null  object
 7   StopID                        714569 non-null  object
 8   PackageID                     714569 non-null  object
 9   planned_service_time_seconds  714569 non-null  float64
 10  depth_cm                      714569 non-null  float64
 11  height_cm                     714569 non-null  float64
 12  weight_cm                     714569 non-null  float64
 13  time_to_arrive                714569 non-null  float64
dtypes: float64(6), object(8)
memory usage: 76.3+ MB

In [10]:
df_eval_route_package_data.describe()

,executor_capacity_cm3,planned_service_time_seconds,depth_cm,height_cm,weight_cm,time_to_arrive
count,7.145690e+05,714569.000000,714569.000000,714569.000000,714569.000000,714569.000000
mean,3.668698e+06,70.413758,33.795002,10.158491,24.548767,1832.104515
std,4.835055e+05,69.740068,9.199817,7.339519,7.334135,612.804355
min,3.114853e+06,1.000000,0.300000,0.000000,0.300000,45.900000
25%,3.313071e+06,37.500000,25.700000,4.800000,17.800000,1367.400000
50%,3.539606e+06,54.300000,32.300000,7.600000,24.100000,1816.300000
75%,4.247527e+06,81.000000,38.600000,12.700000,29.200000,2227.400000
max,4.672280e+06,7325.000000,134.600000,73.700000,95.300000,7179.700000

## 2. Feature Selection

In [13]:
entropy_values = df_eval_route_package_data.apply(calculate_entropy)
# Sort the entropy_values in descending order
entropy_values = entropy_values.sort_values(ascending=False)
entropy_values

PackageID                       19.446714
time_to_arrive                  14.480888
RouteID                         11.540118
departure_time_utc              10.507729
StopID                           9.391532
planned_service_time_seconds     9.081874
starting_point                   8.143111
Zone                             7.867785
date_YYYY_MM_DD                  6.331296
depth_cm                         6.178412
weight_cm                        6.025406
height_cm                        5.595292
station_code                     3.826254
executor_capacity_cm3            2.142974
dtype: float64

## 3. Handling duplicates

In [16]:
df_eval_route_package_data.duplicated().sum()

0