# Route Data Preprocessing

## Utils

In [127]:
import json
from scipy.stats import entropy

def calculate_entropy(col):
    """Calculate entropy of a column in a dataframe.
    
    Args:
        df (pandas.DataFrame): Dataframe containing the column.
        col (str): Name of the column to calculate entropy for.
        
    Returns:
        float: Entropy of the column.
    """
    value_counts = col.value_counts()
    probabilities = value_counts / value_counts.sum()
    return entropy(probabilities, base=2)

## Preprocessing Phase 1

### Overview

In [114]:
import pandas as pd

In [115]:
ROUTE_DATA_PROCESSED_DATASET_PATH = "../datasets/processed/eval_route_data_formatted.json"

df_eval_route = pd.read_json(ROUTE_DATA_PROCESSED_DATASET_PATH)

df_eval_route

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,AH,Zone,AJ,AL,AN,...,XX,AE,PP,UO,RM,SZ,BH,LX,VP,XV
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,1.0,K-21,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RouteID_00337a3a-19c6-4821-9350-ad3cf0532047,DLA4,2018-09-03,14:48:09,3313071.00,NaN,E-4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RouteID_0034b931-97a7-485f-a6b3-b22798489094,DLA4,2018-09-19,15:00:43,3313071.00,NaN,D-1,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RouteID_0085d8a2-71a3-4205-9c46-e62139eca47b,DSE4,2018-07-02,15:18:39,3539605.75,1.0,B-10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RouteID_008bf177-673c-4647-89dd-bf8c13b7c51d,DLA3,2018-07-11,15:30:00,3313071.00,1.0,B-9,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3047,RouteID_feb2d877-9478-474c-8f88-6f93ce2ac6aa,DLA8,2018-06-26,16:35:12,3539605.75,NaN,D-23,1.0,NaN,NaN,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3048,RouteID_feb83237-362d-4234-ab4b-50741a3b1bf6,DCH1,2018-09-15,14:29:45,3313071.00,NaN,None,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3049,RouteID_fedf4c2f-2618-4598-bfb5-ec90822c9a29,DBO3,2018-09-17,12:01:18,4247527.00,NaN,H-2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3050,RouteID_ff30c100-6266-461d-9c56-939775a1defe,DBO1,2018-09-18,13:05:52,4247527.00,NaN,H-7,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
3051,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,1.0,G-18,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN

In [116]:
df_eval_route.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3052 entries, 0 to 3051
Columns: 681 entries, RouteID to XV
dtypes: float64(676), object(5)
memory usage: 15.9+ MB

In [117]:
df_eval_route.describe()

,executor_capacity_cm3,AH,AJ,AL,AN,AP,AS,AY,BA,BB,...,XX,AE,PP,UO,RM,SZ,BH,LX,VP,XV
count,3.052000e+03,734.000000,727.0,683.000000,655.0,621.000000,750.000000,648.0,763.0,667.000000,...,582.000000,727.000000,702.000000,684.0,644.0,746.0,584.0,613.0,573.000000,548.000000
mean,3.670335e+06,1.004087,1.0,1.014641,1.0,1.019324,1.041333,1.0,1.0,1.043478,...,1.008591,1.005502,1.007123,1.0,1.0,1.0,1.0,1.0,1.001745,1.025547
std,4.860622e+05,0.063844,0.0,0.120200,0.0,0.137771,0.199193,0.0,0.0,0.204084,...,0.092368,0.074022,0.084154,0.0,0.0,0.0,0.0,0.0,0.041776,0.157925
min,3.114853e+06,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.0,1.0,1.000000,...,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000
25%,3.313071e+06,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.0,1.0,1.000000,...,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000
50%,3.539606e+06,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.0,1.0,1.000000,...,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000
75%,4.247527e+06,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.0,1.0,1.000000,...,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000
max,4.672280e+06,2.000000,1.0,2.000000,1.0,2.000000,2.000000,1.0,1.0,2.000000,...,2.000000,2.000000,2.000000,1.0,1.0,1.0,1.0,1.0,2.000000,2.000000

### 1. Handling Missing values

First we need to fill the missing nan values for the stops in order to make it easier to perform feature extraction.

In [118]:
# Specify columns to exclude from filling NaN
exclude_columns = ["station_code", "date_YYYY_MM_DD", "departure_time_utc", "executor_capacity_cm3", "Zone"]

# Fill NaN values with 0 only for columns not in the exclude_columns list
df_eval_route[df_eval_route.columns.difference(exclude_columns)] = df_eval_route[df_eval_route.columns.difference(exclude_columns)].fillna(0)

df_eval_route

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,AH,Zone,AJ,AL,AN,...,XX,AE,PP,UO,RM,SZ,BH,LX,VP,XV
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,1.0,K-21,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,RouteID_00337a3a-19c6-4821-9350-ad3cf0532047,DLA4,2018-09-03,14:48:09,3313071.00,0.0,E-4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,RouteID_0034b931-97a7-485f-a6b3-b22798489094,DLA4,2018-09-19,15:00:43,3313071.00,0.0,D-1,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,RouteID_0085d8a2-71a3-4205-9c46-e62139eca47b,DSE4,2018-07-02,15:18:39,3539605.75,1.0,B-10,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,RouteID_008bf177-673c-4647-89dd-bf8c13b7c51d,DLA3,2018-07-11,15:30:00,3313071.00,1.0,B-9,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3047,RouteID_feb2d877-9478-474c-8f88-6f93ce2ac6aa,DLA8,2018-06-26,16:35:12,3539605.75,0.0,D-23,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3048,RouteID_feb83237-362d-4234-ab4b-50741a3b1bf6,DCH1,2018-09-15,14:29:45,3313071.00,0.0,None,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3049,RouteID_fedf4c2f-2618-4598-bfb5-ec90822c9a29,DBO3,2018-09-17,12:01:18,4247527.00,0.0,H-2,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3050,RouteID_ff30c100-6266-461d-9c56-939775a1defe,DBO1,2018-09-18,13:05:52,4247527.00,0.0,H-7,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3051,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,1.0,G-18,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

Now we analyze the missing data for the other columns

In [119]:
missing_count = df_eval_route.isnull().sum()
missing_percentage = missing_count / df_eval_route.shape[0] * 100

# Sort the missing_percentage in descending order
missing_percentage = missing_percentage.sort_values(ascending=False)
# Sort the missing_count in descending order
missing_count = missing_count[missing_percentage.index]

# Print the results
print("Missing values count:\n", missing_count)
print("Missing percentage:\n", missing_percentage)

Missing values count:
 Zone       45
RouteID     0
BF          0
RI          0
TC          0
           ..
VV          0
WH          0
WS          0
WV          0
XV          0
Length: 681, dtype: int64
Missing percentage:
 Zone       1.474443
RouteID    0.000000
BF         0.000000
RI         0.000000
TC         0.000000
             ...
VV         0.000000
WH         0.000000
WS         0.000000
WV         0.000000
XV         0.000000
Length: 681, dtype: float64

Take a look at the rows for which the Zone column is NaN and complete the missing values for the Zone column as the missing percentage for this is low.

In [120]:
# Retrieve the rows with missing values for the Zone column
df_eval_route[df_eval_route["Zone"].isnull()]

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,AH,Zone,AJ,AL,AN,...,XX,AE,PP,UO,RM,SZ,BH,LX,VP,XV
80,RouteID_08c95b99-2162-49aa-bfe3-0266398ac0df,DLA7,2018-09-25,15:45:00,3313071.00,1.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
169,RouteID_1185aa62-d314-40bd-9fb2-90dbe71057e1,DBO2,2018-09-29,13:29:36,3114853.25,1.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
251,RouteID_1905fff4-7264-41d2-9743-9dc40f258e44,DLA9,2018-09-20,13:44:09,3313071.00,0.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
438,RouteID_2e469d92-af48-4f5d-8aec-efd8ee0991eb,DSE5,2018-07-09,15:13:54,3539605.75,1.0,None,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
461,RouteID_3037462e-99c6-48b2-b35d-b8f5855bbbfa,DBO3,2018-09-18,12:25:07,4247527.00,1.0,None,0.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
581,RouteID_3d3a7749-5726-4d8c-9c31-354dd2361af8,DLA7,2018-06-18,17:00:00,3539605.75,1.0,None,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
586,RouteID_3da64d06-23d9-42d9-8cb7-04b730057b8e,DLA8,2018-10-02,16:56:23,3114853.25,0.0,None,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
633,RouteID_4209c56a-f704-4848-b466-9862686e044e,DCH1,2018-06-01,16:18:58,3539605.75,0.0,None,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
706,RouteID_4afe6327-f83a-4454-8567-28a6b0d40afe,DLA9,2018-09-23,13:39:24,3313071.00,0.0,None,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
764,RouteID_51690478-c15c-4e3c-9a79-ba05c119be95,DCH1,2018-09-28,15:03:14,3313071.00,0.0,None,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
824,RouteID_587876a2-40af-4843-b7cf-4bdff6ccb775,DBO1,2018-06-23,13:15:37,3539605.75,0.0,None,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
923,RouteID_6262fb3a-286f-4b8e-b117-9bd548c7713b,DLA7,2018-07-14,16:37:53,3313071.00,1.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1092,RouteID_72db1ed7-4492-4100-ab6e-28c6f201a38b,DLA7,2018-06-14,16:07:11,3539605.75,1.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1128,RouteID_78304aa9-be52-4527-b55b-dd342e6362f6,DCH1,2018-09-29,15:00:12,3114853.25,0.0,None,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1181,RouteID_7e07401c-3a86-444a-a934-628003cb79a2,DLA9,2018-07-01,14:02:41,3539605.75,0.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1227,RouteID_82730dce-dcd2-46f6-a2c4-e8d2831adb65,DLA7,2018-09-25,14:59:36,3313071.00,0.0,None,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1240,RouteID_836c91d5-ed5f-4f85-9d20-2453620ede0b,DCH2,2018-09-08,14:10:26,3313071.00,0.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1319,RouteID_8b5abca1-61a6-417a-8c09-0170a823e72f,DBO3,2018-06-21,12:50:58,3539605.75,1.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1331,RouteID_8c0c3572-8585-4e44-834f-c3d09931c6fb,DBO1,2018-07-16,13:03:07,4247527.00,0.0,None,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1369,RouteID_9098e81b-4b14-4596-b257-041a17b51bcc,DLA3,2018-09-05,15:13:03,3313071.00,0.0,None,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1408,RouteID_95e49ed0-2227-49de-b5f6-8454e819ed75,DBO3,2018-09-10,12:15:00,4247527.00,1.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1449,RouteID_9adda106-1aa3-4463-aa5a-c88b39ae1503,DLA9,2018-09-20,15:00:00,3313071.00,1.0,None,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1470,RouteID_9d2169f0-bf08-4114-8e17-77e5b08210eb,DBO3,2018-08-30,12:15:00,4247527.00,1.0,None,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1484,RouteID_9ee3186d-de31-4ec4-9114-b49f0ef20835,DLA7,2018-09-01,15:45:00,3313071.00,1.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1512,RouteID_a2cecb4a-f896-4935-92c1-a3ed1f1316ac,DLA9,2018-09-16,15:19:02,3313071.00,1.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1521,RouteID_a3e1fec9-ed98-4747-b3fe-d022b2c05eb3,DBO2,2018-09-24,13:45:00,3313071.00,0.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1595,RouteID_ab485ad5-abf3-4bbd-a760-f77569cf95b7,DAU1,2018-09-14,15:30:00,4247527.00,0.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1795,RouteID_c08273f0-6634-43ac-950e-5d0eec974db9,DLA8,2018-09-29,16:15:00,3114853.25,0.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1843,RouteID_c4a872b1-c735-4838-90c6-df9116a49527,DLA9,2018-08-27,16:03:55,3313071.00,0.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1921,RouteID_cc28fc8d-8be9-453f-97bf-5d69c36aa3bc,DAU1,2018-09-16,13:39:04,4247527.00,1.0,None,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1926,RouteID_cc5f8d62-517f-4a7e-9824-4e4ef53d8013,DLA8,2018-07-05,16:19:23,3539605.75,0.0,None,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1959,RouteID_cfdb8e7f-4aa6-4244-8ebb-c569ccae121b,DLA7,2018-07-02,16:07:21,3539605.75,1.0,None,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
1968,RouteID_d122dd76-bc32-40c2-b89e-77a34ee24478,DLA5,2018-09-30,14:34:04,3398021.50,0.0,None,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2056,RouteID_da39a3b5-4f74-45d0-b397-45a7c84d5df5,DLA9,2018-07-13,15:00:00,3313071.00,1.0,None,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2076,RouteID_dc903e50-0251-42df-a58a-e09150e3d9a2,DLA4,2018-10-02,14:15:00,3114853.25,1.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2095,RouteID_dea0f514-d4ca-4153-8495-c873b715d4f8,DCH4,2018-06-23,15:17:54,4672279.50,1.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2128,RouteID_e15c9f15-a8c9-4749-baf1-36573cf85bdc,DLA4,2018-09-26,13:52:50,3313071.00,0.0,None,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2253,RouteID_ee217374-d385-4a41-91c9-07473854748d,DAU1,2018-09-25,13:48:48,4247527.00,0.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2414,RouteID_ff4b942c-0b49-4341-9a32-9e9f27cbc2e3,DLA8,2018-06-02,16:15:00,3539605.75,0.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2513,RouteID_1f9cf412-a08b-4a11-be99-22246bf0c091,DLA5,2018-09-23,14:57:49,3313071.00,1.0,None,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2669,RouteID_66daf97e-fa9a-4394-b5c1-bf6192a2d925,DLA8,2018-06-12,16:34:58,3539605.75,0.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2784,RouteID_9456dae7-bb18-4c60-a63c-5ba86a47a41b,DLA7,2018-06-24,16:00:00,3539605.75,0.0,None,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0
2884,RouteID_be3ef5f3-269a-41b4-8465-5fc581c4426e,DLA8,2018-06-03,17:17:26,3539605.75,1.0,None,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2914,RouteID_cdf6222c-16be-46cb-8dae-91a978cb4d5f,DLA8,2018-07-08,16:36:56,3539605.75,0.0,None,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3048,RouteID_feb83237-362d-4234-ab4b-50741a3b1bf6,DCH1,2018-09-15,14:29:45,3313071.00,0.0,None,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

As we can see these rows represent indepedent rows, so there is no way of knowing the zone for these rows. There is also a pretty low missing percentage for this column > 1.5% so we will drop these rows.

In [121]:
# Drop the rows with missing values for the Zone column
df_eval_route = df_eval_route.dropna(subset=["Zone"])
df_eval_route

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,AH,Zone,AJ,AL,AN,...,XX,AE,PP,UO,RM,SZ,BH,LX,VP,XV
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,1.0,K-21,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,RouteID_00337a3a-19c6-4821-9350-ad3cf0532047,DLA4,2018-09-03,14:48:09,3313071.00,0.0,E-4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,RouteID_0034b931-97a7-485f-a6b3-b22798489094,DLA4,2018-09-19,15:00:43,3313071.00,0.0,D-1,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,RouteID_0085d8a2-71a3-4205-9c46-e62139eca47b,DSE4,2018-07-02,15:18:39,3539605.75,1.0,B-10,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,RouteID_008bf177-673c-4647-89dd-bf8c13b7c51d,DLA3,2018-07-11,15:30:00,3313071.00,1.0,B-9,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3046,RouteID_fe892b64-84ad-48d5-aede-f65d2e4a3123,DLA7,2018-09-09,14:20:14,3313071.00,0.0,E-26,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3047,RouteID_feb2d877-9478-474c-8f88-6f93ce2ac6aa,DLA8,2018-06-26,16:35:12,3539605.75,0.0,D-23,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3049,RouteID_fedf4c2f-2618-4598-bfb5-ec90822c9a29,DBO3,2018-09-17,12:01:18,4247527.00,0.0,H-2,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3050,RouteID_ff30c100-6266-461d-9c56-939775a1defe,DBO1,2018-09-18,13:05:52,4247527.00,0.0,H-7,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3051,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,1.0,G-18,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### 2. Feature Extraction

Every route must have a starting point, so we will extract the starting point from the stops column. THe starting point corresponds to the distribution center.

In [122]:
# For each row extract the columns that have a value of 2
df_eval_route_starting_points = df_eval_route.copy()
df_eval_route_starting_points['starting_point'] = df_eval_route_starting_points.eq(2).idxmax(axis=1)
df_eval_route = df_eval_route_starting_points
df_eval_route

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,AH,Zone,AJ,AL,AN,...,AE,PP,UO,RM,SZ,BH,LX,VP,XV,starting_point
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,1.0,K-21,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UZ
1,RouteID_00337a3a-19c6-4821-9350-ad3cf0532047,DLA4,2018-09-03,14:48:09,3313071.00,0.0,E-4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AI
2,RouteID_0034b931-97a7-485f-a6b3-b22798489094,DLA4,2018-09-19,15:00:43,3313071.00,0.0,D-1,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BU
3,RouteID_0085d8a2-71a3-4205-9c46-e62139eca47b,DSE4,2018-07-02,15:18:39,3539605.75,1.0,B-10,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,HI
4,RouteID_008bf177-673c-4647-89dd-bf8c13b7c51d,DLA3,2018-07-11,15:30:00,3313071.00,1.0,B-9,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,HP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3046,RouteID_fe892b64-84ad-48d5-aede-f65d2e4a3123,DLA7,2018-09-09,14:20:14,3313071.00,0.0,E-26,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,YY
3047,RouteID_feb2d877-9478-474c-8f88-6f93ce2ac6aa,DLA8,2018-06-26,16:35:12,3539605.75,0.0,D-23,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,OX
3049,RouteID_fedf4c2f-2618-4598-bfb5-ec90822c9a29,DBO3,2018-09-17,12:01:18,4247527.00,0.0,H-2,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,YL
3050,RouteID_ff30c100-6266-461d-9c56-939775a1defe,DBO1,2018-09-18,13:05:52,4247527.00,0.0,H-7,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,UI
3051,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,1.0,G-18,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,XL

### 3. Data Reduction

We will use entropy to reduce the number of stops for each route. We will use the entropy of the distribution of the stops for each route to determine the number of stops to keep for each route.

In [123]:
entropy_values = df_eval_route.apply(calculate_entropy)
# Sort the entropy_values in descending order
entropy_values = entropy_values.sort_values(ascending=False)
entropy_values

RouteID               11.554109
departure_time_utc    10.509549
starting_point         8.146905
Zone                   7.862889
date_YYYY_MM_DD        6.329264
                        ...
OZ                     0.639247
FP                     0.638948
TV                     0.635720
VV                     0.634013
JC                     0.630726
Length: 682, dtype: float64

As we can see, the entropy value for the actual stops is extremely low, so we decide to drop all the stops for each route, and just keep the starting point.

In [124]:
# Drop the columns with entropy values less than 1
df_eval_route = df_eval_route.drop(columns=entropy_values[entropy_values < 1].index)
df_eval_route

,RouteID,station_code,date_YYYY_MM_DD,departure_time_utc,executor_capacity_cm3,Zone,starting_point
0,RouteID_00092558-dece-4fb7-8d0d-7d0df3a4864e,DLA8,2018-06-17,17:23:00,3539605.75,K-21,UZ
1,RouteID_00337a3a-19c6-4821-9350-ad3cf0532047,DLA4,2018-09-03,14:48:09,3313071.00,E-4,AI
2,RouteID_0034b931-97a7-485f-a6b3-b22798489094,DLA4,2018-09-19,15:00:43,3313071.00,D-1,BU
3,RouteID_0085d8a2-71a3-4205-9c46-e62139eca47b,DSE4,2018-07-02,15:18:39,3539605.75,B-10,HI
4,RouteID_008bf177-673c-4647-89dd-bf8c13b7c51d,DLA3,2018-07-11,15:30:00,3313071.00,B-9,HP
...,...,...,...,...,...,...,...
3046,RouteID_fe892b64-84ad-48d5-aede-f65d2e4a3123,DLA7,2018-09-09,14:20:14,3313071.00,E-26,YY
3047,RouteID_feb2d877-9478-474c-8f88-6f93ce2ac6aa,DLA8,2018-06-26,16:35:12,3539605.75,D-23,OX
3049,RouteID_fedf4c2f-2618-4598-bfb5-ec90822c9a29,DBO3,2018-09-17,12:01:18,4247527.00,H-2,YL
3050,RouteID_ff30c100-6266-461d-9c56-939775a1defe,DBO1,2018-09-18,13:05:52,4247527.00,H-7,UI
3051,RouteID_ffdd3b7f-9de4-4a0b-8c07-d186bf7f2dee,DLA7,2018-07-08,15:42:06,3539605.75,G-18,XL

In [136]:
ROUTE_DATA_PREPROCESSED_DATASET_PATH = "../datasets/preprocessed/eval_route_data_formatted.json"

df_eval_route_preprocessed = df_eval_route.copy()
df_eval_route_preprocessed_json = df_eval_route_preprocessed.to_json(orient='records')

df_eval_route_preprocessed_json

with open(ROUTE_DATA_PREPROCESSED_DATASET_PATH, 'w') as file:
    json.dump(df_eval_route_preprocessed_json, file, indent=4)